### ISSUE TITLE
[mac-chrome-1920-스터디 모집 게시글] 삭제 버튼 표시 

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-bluestarfish-blueberry-fe#107]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 자신이 올린 글이 아닌데 삭제 버튼이 보입니다
- 게시글 삭제까지 성공합니다

## 재현하는 방법

동작을 재현하는 단계:

1. 스터디 모집 게시판 접속
2. 스터디 모집 게시글 접속

## 예상한 동작

- 본인이 올린 게시글에만 삭제 버튼 표시

## 스크린샷 (옵션)

<img width="1083" alt="image" src="https://github.com/user-attachments/assets/91724eb5-1ddb-4f39-b2ce-09d6d65fa2f3">

**Comment by yeji0214** [comment]
수정했습니다 :)
