### ISSUE TITLE
[Mac-크롬-1080-스터디룸목록페이지] 메인화면에서 더보기 클릭 시, 레이아웃 깨짐

### ISSUE THREAD

**Issue by erica0321** [100-hours-a-week/5-bluestarfish-blueberry-fe#109]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 메인화면에서 스터디룸 목록 하단에 더보기 버튼 클릭 후 페이지 이동하면 레이아웃이 꺼집니다.

## 재현하는 방법

동작을 재현하는 단계:

1. 메인화면 이동
2. 스터디룸 하단에 더보기 버튼 클릭
3. 스터디룸 목록 페이지로 이동 시 레이아웃 깨짐

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 레이아웃이 깨지지 않고 제대로 중앙정렬되어 보임

## 스크린샷 (옵션)
![image](https://github.com/user-attachments/assets/8d0eeeda-6d11-4224-b074-16e617ce68b3)

**Comment by yeji0214** [comment]
수정했습니당 🫐
