### ISSUE TITLE
[mac-chrome-1920-스터디 모집 게시판] 게시글 작성시 로그인한 유저와 작성자명이 다름

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/5-bluestarfish-blueberry-fe#111]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 게시글 작성시 로그인한 유저명과 작성자명이 다름

## 재현하는 방법

동작을 재현하는 단계:

1. 회원 로그인
2. 게시글 작성 페이지 이동
3. 게시글 작성 폼 입력
4. 게시글 작성

## 예상한 동작

- '보이두' 닉네임을 가진 사용자로 로그인 후 게시글 생성
- 생성한 게시글 작성자 이름은 '보이두'로 출력되어야 함

## 스크린샷 (옵션)

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/88ba3287-b661-4895-b2b0-ce885c01dbff">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: Mac
- Browser: Chrome
- Version: ?

## 추가적인 내용 (옵션):

게시글 생성시 모든 작성자명이 동일함 (로그인한 유저가 아닌 다른 유저로 조회됨)

**Comment by yeji0214** [comment]
수정했습니당 🫐
