### ISSUE TITLE
[MAC-크롬-1920-게시글작성] 게시글 작성 오류

### ISSUE THREAD

**Issue by erica0321** [100-hours-a-week/5-bluestarfish-blueberry-fe#112]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 게시글 작성 실패

## 재현하는 방법

동작을 재현하는 단계:

1. 게시글 작성 페이지로 이동
2. 입력값 다 넣기
3. 게시글 작성 버튼 클릭

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 게시글 작성 성공

## 스크린샷 (옵션)

![image](https://github.com/user-attachments/assets/912ef9dc-3b06-42db-bbfd-333fdb1b10f7)

**Comment by yeji0214** [comment]
수정했습니당 🫐
