### ISSUE TITLE
[mac-chrome-1920-쿼리] network 탭에서 유저, 스터디룸 비밀번호 노출 

### ISSUE THREAD

**Issue by erica0321** [100-hours-a-week/5-bluestarfish-blueberry-fe#113]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 유저, 스터디룸 비밀번호가 노출됩니다.

## 재현하는 방법

동작을 재현하는 단계:

1. 네트워크 탭에서 특정 쿼리 확인하면, 해당 응답에 비밀번호가 노출

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 비밀번호 노출이 안됨

## 스크린샷 (옵션)

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/b9fab93b-49ac-4eba-a259-30fd5235d576">

**Comment by DohunHyun** [comment]
수정했습니다.
https://github.com/100-hours-a-week/5-bluestarfish-blueberry-be/pull/152
