### ISSUE TITLE
회원가입 UI 짤림

### ISSUE THREAD

**Issue by BenchPress200** [100-hours-a-week/5-bluestarfish-blueberry-fe#168]
##  버그 설명

- 회원가입 UI 짤림

## 스크린샷 (옵션)
<img width="975" alt="스크린샷 2024-09-01 오후 7 48 01" src="https://github.com/user-attachments/assets/1e7ade2d-b355-451c-82b3-4b5bcdfdc4da">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: Mac
- chrome

**Comment by yeji0214** [comment]
수정했습니당 🫐
