### ISSUE TITLE
게시글 작성 페이지 마우스 커서

### ISSUE THREAD

**Issue by BenchPress200** [100-hours-a-week/5-bluestarfish-blueberry-fe#173]
##  버그 설명

- 게시글 작성페이지에서 게시글 작성 버튼 호버 시,
아무 표시 없음 
- 마우스 커서 표시 제안 !

## 스크린샷 (옵션)

<img width="608" alt="스크린샷 2024-09-01 오후 8 00 28" src="https://github.com/user-attachments/assets/55871b60-031f-4dfe-a698-b69143354a8b">

 

- Mac
- Chrome

**Comment by yeji0214** [comment]
수정했습니당 🫐
