### ISSUE TITLE
모집완료된 룸 찾기 게시글

### ISSUE THREAD

**Issue by BenchPress200** [100-hours-a-week/5-bluestarfish-blueberry-fe#174]
- 모집완료 여부를 사용자가 더 알기 쉽도록 할 수 있으면 좋을 것 같다는 제안 !

## 스크린샷 (옵션)

<img width="1080" alt="스크린샷 2024-09-01 오후 8 08 51" src="https://github.com/user-attachments/assets/cdc4062c-fcd4-46b7-bf52-88252a53fe88">

**Comment by yeji0214** [comment]
수정했습니당 🫐
