### ISSUE TITLE
게시글 페이지 댓글 무한스크롤 동작안함

### ISSUE THREAD

**Issue by BenchPress200** [100-hours-a-week/5-bluestarfish-blueberry-fe#178]
##  버그 설명

- 게시글 페이지 댓글 무한스크롤 동작안함
- 오랜된 댓글은 조회불가능

## 스크린샷 (옵션)

<img width="1279" alt="스크린샷 2024-09-01 오후 8 25 23" src="https://github.com/user-attachments/assets/eea685a9-7e28-406b-8fd5-dd8a224d8160">

**Comment by yeji0214** [comment]
수정했습니당 🫐
