### ISSUE TITLE
게시글 수정시 나의 스터디 항목이 제대로 뜨지 않음

### ISSUE THREAD

**Issue by hyeonheeeee** [100-hours-a-week/5-bluestarfish-blueberry-fe#179]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 게시글 수정시 나의 스터디 항목이 본인 것 뿐만 아니라 다른 사람것까지 뜸

## 재현하는 방법

동작을 재현하는 단계:

1. 게시글 생성 후 수정

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="838" alt="image" src="https://github.com/user-attachments/assets/b9dec3af-4137-414b-aea5-9b70937f0628">

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by yeji0214** [comment]
수정했습니당 🫐
