### ISSUE TITLE
[mac-chrome-1920-정보수정] 개별 정보 수정 불가

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-bluestarfish-blueberry-fe#266]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 프로필 이미지, 닉네임 등 특정 정보만 변경이 불가능합니다.

## 재현하는 방법

동작을 재현하는 단계:

1. 프로필 수정 페이지 접속
2. 이미지 업로드

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 하나의 정보만 수정해도 수정완료 버튼이 활성화되면 좋을 것 같습니다

## 스크린샷 (옵션)

<img width="488" alt="image" src="https://github.com/user-attachments/assets/75ea2cf3-34ae-4b6f-a9f2-2e818c723762">

**Comment by yeji0214** [comment]
수정했습니당 🫐
