### ISSUE TITLE
[mac-chrome-1920-회원 정보 수정] 회원 정보 수정 불가

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/5-bluestarfish-blueberry-fe#268]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 입력 값에 대한 유효성 검사는 통과했지만, 회원 정보 수정이 안됩니다
- "유저데이터 수정 실패" 메시지가 나타납니다
- "payload too large" 가 나타나 이미지 크기를 줄여 수정했더니 동작합니다
- 이미지 크기에 대한 유효성 검사를 넣으면 좋을 것 같습니다!

## 예상한 동작

- 입력 값 유효성 검사 통과 후 수정 버튼을 누르면 회원 정보가 수정됨

## 스크린샷 (옵션)

<img width="1100" alt="image" src="https://github.com/user-attachments/assets/7c52e7c6-42ed-40c0-b835-0679e22d9b2e">

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/cadceec3-ea3e-4105-8db9-7e736a980ba9">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: mac
- Browser chrome

**Comment by boozeal** [comment]
24e79d5f7cc8e94f4e37c5cc4459f574b9408097
