### ISSUE TITLE
[mac-chrome-1920-정보수정] 닉네임 중복 검사 오류

### ISSUE THREAD

**Issue by yoouung** [100-hours-a-week/5-bluestarfish-blueberry-fe#269]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 닉네임 수정하지 않고 중복확인 시 통과됨

## 재현하는 방법

동작을 재현하는 단계:

1. 정보수정 페이지 접속
2. 닉네임 중복확인 버튼 클릭

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 닉네임 수정 시에만 중복 확인 버튼 활성화

## 스크린샷 (옵션)

<img width="388" alt="image" src="https://github.com/user-attachments/assets/c2456a31-3622-4f6b-bc4c-1938b703df9d">

**Comment by boozeal** [comment]
의도한 동작이므로 클로즈
