### ISSUE TITLE
스터디룸 대기방에 url입력으로 접근시 run time error 화면 출력

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/5-bluestarfish-blueberry-fe#274]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 버그 1
- 버그 2

## 재현하는 방법

동작을 재현하는 단계:

1. 주소창에 https://blueberry826.com/wait/101 을 입력한다
2. 인가되지 않은 접근에 대한 alert가 노출된다.
3. runtime error 메세지가 노출된다.

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 메인 페이지로 이동한다.

## 스크린샷 (옵션)

<img width="992" alt="image" src="https://github.com/user-attachments/assets/32d4dcca-994f-42f2-8117-bdbfccc78036">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [MAC]
- Browser [chrome]

**Comment by boozeal** [comment]
if (location.state?.authorized) {
      // 사용자가 인가된 경우, sessionStorage에 인가 상태 저장
      sessionStorage.setItem("authorized", "true");
    } else if (!authorizedInStorage) {
      // 새로고침이 아닌 도메인 직접 접근 시 (location.state가 없고, 인가되지 않은 경우)
      alert("인가되지 않은 접근입니다.");
      navigate("/");
    }
    세션 스토리지에 저장해서 close
