### ISSUE TITLE
회원가입 페이지 이메일 중복시 헬퍼텍스트

### ISSUE THREAD

**Issue by DohunHyun** [100-hours-a-week/5-bluestarfish-blueberry-fe#299]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 이미 회원가입한 이메일에 대해서 헬퍼텍스트 내용이 상세하게 나오면 좋겠습니다.

<img width="401" alt="스크린샷 2024-09-18 오후 7 37 04" src="https://github.com/user-attachments/assets/a41b2d48-3518-46ee-bcea-8c854b668d68">

**Comment by boozeal** [comment]
누클완
