### ISSUE TITLE
스터디 게시글에서 스터디룸 썸네일 클릭시 이동하지 않음

### ISSUE THREAD

**Issue by hyeonheeeee** [100-hours-a-week/5-bluestarfish-blueberry-fe#343]
스터디 게시글에서 스터디룸 썸네일 클릭시 해당 스터디 룸으로 이동하지 않음

현재는 "인가되지 않은 접근입니다." 로 alert 발생

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/002c6e6b-e7f7-4707-b0b1-4ebe88394e01">

**Comment by boozeal** [comment]
완료
