### ISSUE TITLE
스터디룸 생성 - 스터디 룸 생성시 이미지 크기 이슈

### ISSUE THREAD

**Issue by hyeonheeeee** [100-hours-a-week/5-bluestarfish-blueberry-fe#349]
스터디 룸 생성시 용량이 큰 이미지를 넣으면 413 에러 발생
이미지 크기 제한 필요

**Comment by boozeal** [comment]
기존 nginx에서 1MB 제한을 10MB로 늘려서 close
프론트엔드 로직도 10MB로 변경
